### PR TITLE
Update GameMode vtable signature

### PR DESCRIPTION
**Pull request by Isuejkeizieuejeiie**
Updated GameMode vtable signature

### CODE REVIEW

**Comment by Intoprelised** [comment]
I might be stupid but I'm pretty sure this signature does not work for 1.18.12 nor 1.18.30/1.18.31

**Comment by Isuejkeizieuejeiie** [comment]
It supports 1.19.81.1, 1.19.80.1, 1.19.72, 1.19.71.2, 1.19.70.2 and 1.19.63

**Comment by Isuejkeizieuejeiie** [comment]
> It supports 1.19.81.1, 1.19.80.1, 1.19.72, 1.19.71.2, 1.19.70.2 and 1.19.63

Well, I'm stupid lmao, I didn't see you were going to support 1.18 and not 1.19, ima update my pull request soon

**Comment by Intoprelised** [comment]
Thank you very much this is something we have needed for a while now

If I may, how do you find this signature? If you would not like to disclose here message me on discord and if you don't want to whatever ignore this. (Intop#6824)

**Comment by Intoprelised** [comment]
I have found the sig myself, thank you for the contribution if you would like to do anything else we would appreciate if you focus on the 1.18.31 branch. Preferably inventory transactions

**Comment by Isuejkeizieuejeiie** [comment]
I was about to commit lol

If you want to compare, I found this one : 48 8D ? ? ? ? ? 48 89 01 48 89 51 08 48 C7 41 10 FF FF FF FF C7 41 18 FF FF FF FF 44 88 61 1C 4C 89 61 20 4C 89 61 28 44 89 61 30 F2 0F 10 ? ? ? ? ? F2 0F 11 41 34 8B ? ? ? ? ? 89 41 3C

**Pull request closed without merging**
