### PR TITLE
Xello12121's PR but without merge conflicts

### PR DESCRIPTION
**Pull request by ghost**
[[Update] Add CAttribute.h to CMakeLists.txt](https://github.com/NRGJobro/Horion-Open-SRC/commit/17bc9b2b5ec48115363d809ff38025bb1b4b9286)
[[Update] Xello12121's PR but without merge conflicts](https://github.com/NRGJobro/Horion-Open-SRC/commit/faaab2cc3e793e55aa18ece291b00801e48f046d)

### CODE REVIEW

**Comment by ghost** [comment]
Seems that the addition of the `Notifications` module as `Notifications.cpp` & `Notifications.h` is culprit for failing builds.

**Comment by Intoprelised** [comment]
Going to let NRG review it, not sure if I like these changes

**Comment by ghost** [comment]
> Going to let NRG review it, not sure if I like these changes

Alr.

**Comment by NRGJobro** [comment]
Looks hot

**Pull request merged**
