### PR TITLE
Client Theme (Pre 1.17.11)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
```	
static auto ClientThemes = moduleMgr->getModule<ClientTheme>();
	if (ClientThemes->Theme.selected == 1) {
		DrawUtils::fillRectangle(rectPos, MC_Color(15, 30, 50), 1.0f);
	} else {
		DrawUtils::fillRectangle(rectPos, moduleColor, 1.0f);
	}
	if (ClientThemes->Theme.selected == 1) {
		DrawUtils::drawRectangle(rectPos, MC_Color(30, 110, 200), 1.f, 0.5f);
	} else {
		DrawUtils::drawRectangle(rectPos, brightModuleBlendColor, 1.f, 0.5f);
	}
```

couldn't this be compacted into a single if else statement?

**Comment by ghost** [comment]
yea it could be ill fix

**Comment by ghost** [comment]
Also i'm pretty sure there's a typo in 
```
ClientTheme::ClientTheme() : IModule(0, Category::VISUAL, "Go for a retro style or streanline") {
```

shouldn't it be "streamline" instead of "streanline", correct me if im wrong.

**Comment by NRGJobro** [comment]
Im too lazy to look at this rn but it looks good. Code can be simplified too. Also revert the timer stuff back to int

**Comment by ghost** [comment]
> Im too lazy to look at this rn but it looks good. Code can be simplified too. Also revert the timer stuff back to int

ig i could try it out rn

**Comment by NRGJobro** [comment]
> > Im too lazy to look at this rn but it looks good. Code can be simplified too. Also revert the timer stuff back to int
> 
> ig i could try it out rn

He sent screenshots and its nice

**Comment by NRGJobro** [comment]
I would just prefer the Int timer bec thats how it is in MC its self lol

**Comment by ghost** [comment]
ah then jus revert the timer stuff and merge.

**Comment by NRGJobro** [comment]
Tru

**Comment by ghost** [comment]
ok i fixed it

**Comment by ghost** [comment]
commit n push

**Comment by NRGJobro** [comment]
Love it

**Comment by NRGJobro** [comment]
Waiting for MSBuild then ill pull just to be safe

**Comment by ghost** [comment]
gang shit

**Comment by ghost** [comment]
yeet

**Pull request merged**
